// Package bridgegen 生成 Go c-shared 插件所需的固定 Native ABI 导出入口。
package bridgegen

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const headerName = "zzNativeBridge.h"
const exportName = "zzNativeBridge.go"
const supportName = "zzNativeBridgeSupport.go"

// Options 描述桥接文件目标目录、Go 包名和 SDK 导入路径。
type Options struct {
	OutputDirectory string
	PackageName     string
	SDKImportPath   string
}

// Generate 写入可重复生成的 c-shared ABI 桥；只覆盖三个固定 zzNativeBridge 文件。
//
// 生成文件不包含作者业务逻辑。目录、包名或导入路径非法时不写入任何文件；写入采用临时文件
// 原子替换，避免中断后留下半个 Go 源文件。
func Generate(options Options) error {
	if options.OutputDirectory == "" || !validIdentifier(options.PackageName) || options.SDKImportPath == "" {
		return errors.New("桥接生成参数无效")
	}
	if err := os.MkdirAll(options.OutputDirectory, 0o755); err != nil {
		return err
	}
	files := map[string]string{
		headerName:  nativeHeader,
		exportName:  fmt.Sprintf(nativeExportTemplate, options.PackageName, options.SDKImportPath),
		supportName: fmt.Sprintf(nativeSupportTemplate, options.PackageName),
	}
	for name, content := range files {
		path := filepath.Join(options.OutputDirectory, name)
		temporaryPath := path + ".new"
		if err := os.WriteFile(temporaryPath, []byte(content), 0o644); err != nil {
			return err
		}
		if err := os.Rename(temporaryPath, path); err != nil {
			_ = os.Remove(temporaryPath)
			return err
		}
	}
	return nil
}

// validIdentifier 校验生成代码使用的 Go 包名；生成器不接受关键字或路径片段。
func validIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for index, character := range value {
		if character == '_' || character >= 'a' && character <= 'z' || index > 0 && character >= '0' && character <= '9' {
			continue
		}
		return false
	}
	return !strings.Contains(" break default func interface select case defer go map struct chan else goto package switch const fallthrough if range type continue for import return var ", " "+value+" ")
}

const nativeHeader = `#ifndef SPRAK_CAPTURE_GO_NATIVE_BRIDGE_H
#define SPRAK_CAPTURE_GO_NATIVE_BRIDGE_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const uint8_t *pointer;
    size_t length;
} NativeByteSlice;

typedef struct {
    uint32_t apiVersion;
    NativeByteSlice manifest;
    NativeByteSlice configuration;
} NativeExtensionInitRequest;

typedef struct {
    const uint8_t *pointer;
    size_t length;
    void *releaseContext;
    void (*release)(void *, const uint8_t *, size_t);
} NativeExtensionBuffer;

typedef struct {
    uint32_t apiVersion;
    void *pluginContext;
    int32_t (*invoke)(void *, NativeByteSlice, NativeExtensionBuffer *);
    void (*stop)(void *);
    void (*destroy)(void *);
} NativeExtensionExports;

extern int32_t goCaptureInvoke(void *, NativeByteSlice, NativeExtensionBuffer *);
extern void goCaptureStop(void *);
extern void goCaptureDestroy(void *);

void *nativeContextCreate(uint64_t);
uint64_t nativeContextID(void *);
void nativeContextFree(void *);
void nativeExportsSet(NativeExtensionExports *, void *);
void nativeBufferSet(NativeExtensionBuffer *, void *, size_t);

#endif
`

const nativeExportTemplate = `// Code generated by sprak-plugin-gen; DO NOT EDIT.
package %s

/*
#include "zzNativeBridge.h"
#include <stdlib.h>
*/
import "C"

import (
	"math"
	"unsafe"

	pluginsdk %q
)

// copyNativeSlice 在 ABI 回调内复制宿主切片；非零长度空指针或 GoBytes 长度溢出明确失败。
func copyNativeSlice(value C.NativeByteSlice) ([]byte, bool) {
	if value.length == 0 {
		return []byte{}, true
	}
	if value.pointer == nil || uint64(value.length) > uint64(math.MaxInt32) {
		return nil, false
	}
	return C.GoBytes(unsafe.Pointer(value.pointer), C.int(value.length)), true
}

//export capture_extension_init
func capture_extension_init(request *C.NativeExtensionInitRequest, exports *C.NativeExtensionExports) C.int32_t {
	if request == nil || exports == nil || uint32(request.apiVersion) != pluginsdk.NativeAPIVersion() {
		return -1
	}
	manifest, manifestOK := copyNativeSlice(request.manifest)
	configuration, configurationOK := copyNativeSlice(request.configuration)
	if !manifestOK || !configurationOK {
		return -2
	}
	runtimeID, err := pluginsdk.StartNative(manifest, configuration)
	if err != nil {
		return -3
	}
	context := C.nativeContextCreate(C.uint64_t(runtimeID))
	if context == nil {
		pluginsdk.DestroyNative(runtimeID)
		return -4
	}
	C.nativeExportsSet(exports, context)
	return 0
}

//export goCaptureInvoke
func goCaptureInvoke(context unsafe.Pointer, request C.NativeByteSlice, output *C.NativeExtensionBuffer) C.int32_t {
	if context == nil || output == nil {
		return -1
	}
	requestBytes, ok := copyNativeSlice(request)
	if !ok {
		return -2
	}
	action, err := pluginsdk.InvokeNative(uint64(C.nativeContextID(context)), requestBytes)
	if err != nil || len(action) == 0 {
		return -3
	}
	pointer := C.CBytes(action)
	if pointer == nil {
		return -4
	}
	C.nativeBufferSet(output, pointer, C.size_t(len(action)))
	return 0
}

//export goCaptureStop
func goCaptureStop(context unsafe.Pointer) {
	if context != nil {
		pluginsdk.StopNative(uint64(C.nativeContextID(context)))
	}
}

//export goCaptureDestroy
func goCaptureDestroy(context unsafe.Pointer) {
	if context != nil {
		pluginsdk.DestroyNative(uint64(C.nativeContextID(context)))
		C.nativeContextFree(context)
	}
}
`

const nativeSupportTemplate = `// Code generated by sprak-plugin-gen; DO NOT EDIT.
package %s

/*
#include "zzNativeBridge.h"
#include <stdlib.h>

// 释放宿主已经复制完成的动作 JSON；pointer 必须保持 nativeBufferSet 写入的原值。
static void releaseNativeBuffer(void *context, const uint8_t *pointer, size_t length) {
    (void)context;
    (void)length;
    free((void *)pointer);
}

// 在 C 堆保存实例编号，避免让宿主持有 Go 指针。
void *nativeContextCreate(uint64_t identifier) {
    uint64_t *context = (uint64_t *)malloc(sizeof(uint64_t));
    if (context != NULL) {
        *context = identifier;
    }
    return context;
}

// 读取 C 堆中的实例编号；仅在非空有效上下文回调期间调用。
uint64_t nativeContextID(void *context) {
    return *((uint64_t *)context);
}

// 销毁实例后释放 C 上下文；不得早于最后一次回调。
void nativeContextFree(void *context) {
    free(context);
}

// 按宿主 ABI 固定字段顺序填充导出表。
void nativeExportsSet(NativeExtensionExports *exports, void *context) {
    exports->apiVersion = 2;
    exports->pluginContext = context;
    exports->invoke = goCaptureInvoke;
    exports->stop = goCaptureStop;
    exports->destroy = goCaptureDestroy;
}

// 把 C.CBytes 所有权移交宿主，并登记唯一释放回调。
void nativeBufferSet(NativeExtensionBuffer *output, void *pointer, size_t length) {
    output->pointer = (const uint8_t *)pointer;
    output->length = length;
    output->releaseContext = NULL;
    output->release = releaseNativeBuffer;
}
*/
import "C"
`
