// Code generated by sprak-plugin-gen; DO NOT EDIT.
package main

/*
#include "zzNativeBridge.h"
#include <stdlib.h>
*/
import "C"

import (
	"math"
	"unsafe"

	pluginsdk "sprakcapture/plugin-sdk-go"
)

// copyNativeSlice 在 ABI 回调内复制宿主切片；非零长度空指针或 GoBytes 长度溢出明确失败。
func copyNativeSlice(value C.NativeByteSlice) ([]byte, bool) {
	if value.length == 0 {
		return []byte{}, true
	}
	if value.pointer == nil || uint64(value.length) > uint64(math.MaxInt32) {
		return nil, false
	}
	return C.GoBytes(unsafe.Pointer(value.pointer), C.int(value.length)), true
}

//export capture_extension_init
func capture_extension_init(request *C.NativeExtensionInitRequest, exports *C.NativeExtensionExports) C.int32_t {
	if request == nil || exports == nil || uint32(request.apiVersion) != pluginsdk.NativeAPIVersion() {
		return -1
	}
	manifest, manifestOK := copyNativeSlice(request.manifest)
	configuration, configurationOK := copyNativeSlice(request.configuration)
	if !manifestOK || !configurationOK {
		return -2
	}
	runtimeID, err := pluginsdk.StartNative(manifest, configuration)
	if err != nil {
		return -3
	}
	context := C.nativeContextCreate(C.uint64_t(runtimeID))
	if context == nil {
		pluginsdk.DestroyNative(runtimeID)
		return -4
	}
	C.nativeExportsSet(exports, context)
	return 0
}

//export goCaptureInvoke
func goCaptureInvoke(context unsafe.Pointer, request C.NativeByteSlice, output *C.NativeExtensionBuffer) C.int32_t {
	if context == nil || output == nil {
		return -1
	}
	requestBytes, ok := copyNativeSlice(request)
	if !ok {
		return -2
	}
	action, err := pluginsdk.InvokeNative(uint64(C.nativeContextID(context)), requestBytes)
	if err != nil || len(action) == 0 {
		return -3
	}
	pointer := C.CBytes(action)
	if pointer == nil {
		return -4
	}
	C.nativeBufferSet(output, pointer, C.size_t(len(action)))
	return 0
}

//export goCaptureStop
func goCaptureStop(context unsafe.Pointer) {
	if context != nil {
		pluginsdk.StopNative(uint64(C.nativeContextID(context)))
	}
}

//export goCaptureDestroy
func goCaptureDestroy(context unsafe.Pointer) {
	if context != nil {
		pluginsdk.DestroyNative(uint64(C.nativeContextID(context)))
		C.nativeContextFree(context)
	}
}
