// Code generated by sprak-plugin-gen; DO NOT EDIT.
package main

/*
#include "zzNativeBridge.h"
#include <stdlib.h>

// 释放宿主已经复制完成的动作 JSON；pointer 必须保持 nativeBufferSet 写入的原值。
static void releaseNativeBuffer(void *context, const uint8_t *pointer, size_t length) {
    (void)context;
    (void)length;
    free((void *)pointer);
}

// 在 C 堆保存实例编号，避免让宿主持有 Go 指针。
void *nativeContextCreate(uint64_t identifier) {
    uint64_t *context = (uint64_t *)malloc(sizeof(uint64_t));
    if (context != NULL) {
        *context = identifier;
    }
    return context;
}

// 读取 C 堆中的实例编号；仅在非空有效上下文回调期间调用。
uint64_t nativeContextID(void *context) {
    return *((uint64_t *)context);
}

// 销毁实例后释放 C 上下文；不得早于最后一次回调。
void nativeContextFree(void *context) {
    free(context);
}

// 按宿主 ABI 固定字段顺序填充导出表。
void nativeExportsSet(NativeExtensionExports *exports, void *context) {
    exports->apiVersion = 2;
    exports->pluginContext = context;
    exports->invoke = goCaptureInvoke;
    exports->stop = goCaptureStop;
    exports->destroy = goCaptureDestroy;
}

// 把 C.CBytes 所有权移交宿主，并登记唯一释放回调。
void nativeBufferSet(NativeExtensionBuffer *output, void *pointer, size_t length) {
    output->pointer = (const uint8_t *)pointer;
    output->length = length;
    output->releaseContext = NULL;
    output->release = releaseNativeBuffer;
}
*/
import "C"
